# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('groups', models.CharField(default='', max_length=45)),
                ('place', models.CharField(default='', max_length=45)),
                ('datetime', models.DateTimeField(default='')),
                ('image_url', models.CharField(default='images/default.jpg', max_length=256)),
            ],
            options={
                'db_table': 'shows',
            },
        ),
    ]
